FROM nvidia/cuda:11.0.3-base-ubuntu18.04

ARG VER_CUDA=11.0
ARG VER_RAPIDS=21.12
ARG CONDA_INSTALLER=Miniconda3-latest-Linux-x86_64.sh
ARG CONDA_ROOT=/opt/miniconda3

#ARG PIP_OPTS="--disable-pip-version-check --no-cache-dir"


RUN echo building... \
    && cd /tmp/ \
    && mv /etc/apt/sources.list.d /etc/apt/sources.list.d.bak \
    && apt-get update \
    && apt-get install -y wget libxml2 \
    && apt-get clean \
    && wget -q https://repo.anaconda.com/miniconda/$CONDA_INSTALLER \
    && sh $CONDA_INSTALLER -b -p $CONDA_ROOT \
    && $CONDA_ROOT/bin/conda init \
    && $CONDA_ROOT/bin/conda create -n hypergbm -c rapidsai -c nvidia -c conda-forge python=3.8 cudatoolkit=$VER_CUDA cudf=$VER_RAPIDS cuml=$VER_RAPIDS  hypergbm jupyterlab jupyterlab_widgets ipywidgets \
    && echo conda activate hypergbm >> /root/.bashrc \
    && $CONDA_ROOT/bin/conda clean -a -y -q \
    && rm -rf /var/cache \
    && rm -rf /root/.cache \
    && rm -rf /tmp/*

ARG PIP_OPTS="--disable-pip-version-check --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple/"

RUN echo building... \
    && bash -i -c "pip install $PIP_OPTS hypernets-jupyter-widget experiment-visualization experiment-notebook-widget" \
    && mkdir -p /opt/datacanvas \
    && cp -r $CONDA_ROOT/envs/hypergbm/lib/python3.8/site-packages/hypergbm/examples /opt/datacanvas/ \
    && echo "#!/bin/bash\n\ncd /opt\n$CONDA_ROOT/envs/hypergbm/bin/jupyter lab --notebook-dir=/opt/datacanvas --ip=0.0.0.0 --port=\$NotebookPort --no-browser --allow-root --NotebookApp.token=\$NotebookToken" > /entrypoint.sh \
    && chmod +x /entrypoint.sh \
    && rm -rf /var/cache \
    && rm -rf /root/.cache \
    && rm -rf /tmp/*

EXPOSE 8888

ENV NotebookToken="" \
    NotebookPort=8888

CMD ["/entrypoint.sh"]

# docker run --rm --name hypergbm -p 8830:8888 -e NotebookToken=your-token  datacanvas/hypergbm
