# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.6]
        exclude:
          - os: macos-latest
            python-version: 3.6

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dask==2021.1.1 distributed==2021.1.1 dask-ml featuretools python-geohash nlp-primitives
        pip install git+https://github.com/DataCanvasIO/Hypernets
        pip install -r requirements.txt
        pip install -q pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip list
    - name: Test with pytest
      run: |
        pytest --cov=hypergbm --durations=30
